export const seedHolding = [
  {
    symbol: "AAPL",
    name: "Apple ",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AAPL.svg",
    position: 1,
    cost: 100,
    targetPct: 20,
    price: 143.21,
    value: 143.21,
    unrealizedGain: 43.21,
    unrealizedGainPct: 43.21,
    color: "#b93848",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com ",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMZN.svg",
    position: 1.36,
    cost: 91.58,
    targetPct: 20,
    price: 91.58,
    value: 124.55,
    unrealizedGain: 0,
    unrealizedGainPct: 0,
    color: "#32af9e",
  },
  {
    symbol: "NFLX",
    name: "Netflix ",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/NFLX.svg",
    position: 0.39,
    cost: 317.83,
    targetPct: 20,
    price: 317.83,
    value: 123.95,
    unrealizedGain: 0,
    unrealizedGainPct: 0,
    color: "#8be482",
  },
  {
    symbol: "TSLA",
    name: "Tesla ",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/TSLA.svg",
    position: 0.8,
    cost: 156.8,
    targetPct: 20,
    price: 156.8,
    value: 125.44,
    unrealizedGain: 0,
    unrealizedGainPct: 0,
    color: "#e40665",
  },
  {
    symbol: "DIS",
    name: "Walt Disney",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/DIS.svg",
    position: 1.33,
    cost: 94.15,
    targetPct: 20,
    price: 94.15,
    value: 125.22,
    unrealizedGain: 0,
    unrealizedGainPct: 0,
    color: "#8c28af",
  },
];
